name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest 
      - run: bun install 
      - run: bun vite build
      - run: bun preview &
      - run: sleep 60
      - run: curl -sI http://localhost:4173/
      - run: killall bun

