name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
          bun-version: 1.1.13

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun build
